# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM gcr.io/google-samples/grpc-cxx:1.1.0

RUN dnf -y install glibc-static libstdc++-static

COPY . /code
WORKDIR /code

RUN PKG_CONFIG_PATH=/usr/local/lib/pkgconfig make greeter_server_static

CMD ["cat", "greeter_server_static"]
