description: Test Setup Instructions with CMake and vcpkg
filename: ci/cloudbuild-setup-vcpkg.yaml
github:
  name: cpp-samples
  owner: GoogleCloudPlatform
  pullRequest:
    branch: ^main$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
name: cpp-samples-setup-vcpkg-pr
substitutions:
  _TRIGGER_TYPE: pr
