description: Test Setup Instructions with CMake and Conda
filename: ci/cloudbuild-setup-conda.yaml
github:
  name: cpp-samples
  owner: GoogleCloudPlatform
  pullRequest:
    branch: ^main$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
name: cpp-samples-setup-conda-pr
substitutions:
  _TRIGGER_TYPE: pr
