---
name: style

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  formatting:
    name: formatting
    runs-on: ubuntu-20.04
    steps:
      - name: install cmake-format
        run: pip install cmakelang==0.6.13
      - uses: actions/checkout@v3
      - name: clang-format
        run: git ls-files -z | grep -zE '\.(cc|h)$' | xargs -P 2 -n 50 -0 clang-format-10 -i
      - name: cmake-format
        run: >
          git ls-files -z | grep -zE '((^|/)CMakeLists\.txt|\.cmake)$' |
          xargs -P 2 -n 1 -0 /home/runner/.local/bin/cmake-format -i
      - name: check-diff
        run: git diff --ignore-submodules=all --color --exit-code .
